"""Emit firmware/src/assets/codex_animation.h with 4 RGB565 frames + frame table.

Mirrors build_clawd_animation.py exactly. Reads:
  firmware/tools/codex_frames/codex_{idle,blink,wave,sleep}.png
Writes:
  firmware/src/assets/codex_animation.h
"""
from __future__ import annotations
import struct
from pathlib import Path
from PIL import Image

FRAMES = ["idle", "blink", "wave", "sleep"]
TARGET = (160, 160)


def rgba_to_rgb565_le(rgba, bg=(0, 0, 0)):
    r, g, b, a = rgba
    if a < 128:
        r, g, b = bg
    else:
        r = (r * a + bg[0] * (255 - a)) // 255
        g = (g * a + bg[1] * (255 - a)) // 255
        b = (b * a + bg[2] * (255 - a)) // 255
    v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return struct.pack("<H", v)


def encode_frame(img: Image.Image) -> bytes:
    img = img.convert("RGBA").resize(TARGET, Image.NEAREST)
    out = bytearray()
    for y in range(img.height):
        for x in range(img.width):
            out += rgba_to_rgb565_le(img.getpixel((x, y)))
    return bytes(out)


def chunkify_hex(data: bytes, per_line: int = 16) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append(", ".join(f"0x{b:02x}" for b in chunk))
    return ",\n    ".join(lines)


def main() -> int:
    src_dir = Path(__file__).parent / "codex_frames"
    out_path = Path(__file__).parent.parent / "src" / "assets" / "codex_animation.h"

    parts = []
    for name in FRAMES:
        png = src_dir / f"codex_{name}.png"
        if not png.exists():
            raise SystemExit(f"missing {png}")
        data = encode_frame(Image.open(png))
        parts.append((name.upper(), len(data), chunkify_hex(data)))

    lines = [
        "// Auto-generated by firmware/tools/build_codex_animation.py — do not edit",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace assets {",
        "",
        f"constexpr int CODEX_FRAME_W = {TARGET[0]};",
        f"constexpr int CODEX_FRAME_H = {TARGET[1]};",
        f"constexpr int CODEX_FRAME_COUNT = {len(FRAMES)};",
        "",
    ]
    for upper, size, body in parts:
        lines.append(f"constexpr uint8_t CODEX_{upper}_DATA[] = {{")
        lines.append(f"    {body}")
        lines.append("};")
        lines.append(f"static_assert(sizeof(CODEX_{upper}_DATA) == {size}, "
                     f"\"CODEX_{upper}_DATA size mismatch\");")
        lines.append("")

    lines.append("constexpr const uint8_t* const CODEX_FRAMES[CODEX_FRAME_COUNT] = {")
    for upper, _, _ in parts:
        lines.append(f"    CODEX_{upper}_DATA,")
    lines.append("};")
    lines.append("constexpr int CODEX_FRAME_SIZES[CODEX_FRAME_COUNT] = {")
    for _, size, _ in parts:
        lines.append(f"    {size},")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace assets")
    lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path} ({sum(s for _, s, _ in parts)} bytes, {len(FRAMES)} frames)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
