"""Rescale source sprite PNGs to a fixed target size and emit C++ headers.

The plan originally called for 480x480 -> 320x240 rescaling, but the real
upstream asset is `assets/logo_80.png` (80x80 RGBA). We upscale 2x via
nearest-neighbor to 160x160 and center the result on the 320x240 panel from
within the LVGL overlay.

Usage:
    python3 firmware/tools/rescale_sprites.py \
        --in assets --out firmware/src/assets \
        --target 160x160 --source logo_80.png

Output: `<out>/clawd_sprite.h` (always renamed to clawd_sprite regardless of
the input filename), declaring assets::CLAWD_W, CLAWD_H, CLAWD_DATA[] as
little-endian RGB565 bytes consumable by an lv_img_dsc_t.
"""
from __future__ import annotations

import argparse
import struct
from pathlib import Path

try:
    from PIL import Image
except ImportError as exc:  # pragma: no cover - import-time
    raise SystemExit("install Pillow: pip3 install --user Pillow") from exc


def to_rgb565(rgb: tuple[int, int, int]) -> int:
    r, g, b = rgb
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def emit_header(img: Image.Image, name: str, out_path: Path) -> None:
    img = img.convert("RGB")
    pixels = []
    for y in range(img.height):
        for x in range(img.width):
            pixels.append(to_rgb565(img.getpixel((x, y))))
    raw = b"".join(struct.pack("<H", p) for p in pixels)
    hex_lines = []
    for i in range(0, len(raw), 16):
        chunk = raw[i:i + 16]
        hex_lines.append(", ".join(f"0x{b:02x}" for b in chunk))
    body = ",\n    ".join(hex_lines)
    upper = name.upper()
    out_path.write_text(
        "// Auto-generated by firmware/tools/rescale_sprites.py — do not edit.\n"
        "#pragma once\n"
        "#include <cstdint>\n"
        "\n"
        "namespace assets {\n"
        f"constexpr int {upper}_W = {img.width};\n"
        f"constexpr int {upper}_H = {img.height};\n"
        f"constexpr uint8_t {upper}_DATA[] = {{\n"
        f"    {body}\n"
        "};\n"
        "}  // namespace assets\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--in", dest="in_dir", required=True,
                    help="source directory containing the input PNG")
    ap.add_argument("--out", dest="out_dir", required=True,
                    help="destination directory for the generated header")
    ap.add_argument("--target", default="160x160",
                    help="WxH target size (default: 160x160)")
    ap.add_argument("--source", default="logo_80.png",
                    help="source PNG filename inside --in (default: logo_80.png)")
    ap.add_argument("--name", default="clawd",
                    help="symbol/file base name (default: clawd)")
    args = ap.parse_args()

    in_dir = Path(args.in_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    tw, th = map(int, args.target.lower().split("x"))
    src = in_dir / args.source
    if not src.exists():
        raise SystemExit(f"source not found: {src}")

    img = Image.open(src).resize((tw, th), Image.NEAREST)
    out_file = out_dir / f"{args.name}_sprite.h"
    emit_header(img, args.name, out_file)
    print(f"wrote {out_file} ({tw}x{th}, {tw * th * 2} bytes RGB565)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
